export const FETCH_EXCHANGE_RATE = 'FETCH_EXCHANGE_RATE'
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCESS'
export const FETCH_EXCHANGE_RATE_ERROR = 'FETCH_EXCHANGE_RATE_ERROR'

export const FETCH_CURRENCIES = 'FETCH_CURRENCIES'
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR'

export const FETCH_HISTORY = 'FETCH_HISTORY'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_ERROR = 'FETCH_HISTORY_ERROR'

export const EXCHANGE_CURRENCY = 'EXCHANGE_CURRENCY'

export const SWAP_POCKETS = 'SWAP_POCKETS'
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT'
